import ying from "../../assets/ying.png"

const Members = {
    "members":  {
            "exec": [
                {
                    "id": 0,
                    "name": "Ying Lin",
                    "role": "Chief Executive Officer",
                    "major": "Computer Science",
                    "email": "ceo@icb.berkeley.edu",
                    "quote": "Great things come from hard work and perseverance",
                    "linkedin": "https://www.linkedin.com/in/yinglin2/",
                    "pic": ying,
                },
                {
                    "id": 1 ,
                    "name": "Kimberly Thai",
                    "role": "Chief Financial Officer",
                    "major": "Psychology",
                    "email": "cfo@icb.berkeley.edu",
                    "quote": "Believe it!",
                    "linkedin": "https://www.linkedin.com/in/thai-kimberly/",
                    "pic": ying,
                }, 
                {
                    "id": 2,
                    "name": "Kelly Ye",
                    "role": "Chief Health Officer",
                    "major": "Computer Science",
                    "email": "cho@icb.berkeley.edu",
                    "quote": "Failing my way to success",
                    "linkedin": "https://www.linkedin.com/in/kelly-ye-400041163/",
                    "pic": ying,
                },
                {
                    "id": 3,
                    "name": "Kaleen Chen",
                    "role": "Chief Marketing Officer",
                    "major": "Computer Science",
                    "email": "cmo@icb.berkeley.edu",
                    "quote": "be obsessed with your own potential",
                    "linkedin": "https://www.linkedin.com/in/kaleen-chen-00a6a5168/",
                    "pic": ying,
                },
                {
                    "id": 4,
                    "name": "Adin Esberg",
                    "role": "Chief Operations Officer",
                    "major": "Cognitive Science + Society and Environment",
                    "email": "coo@icb.berkeley.edu",
                    "quote": "Reimagine the world in a radically different way",
                    "linkedin": "https://www.linkedin.com/in/adin-esberg/",
                    "pic": ying,
                },
                {
                    "id": 5,
                    "name": "Diya Chakraborti",
                    "role": "Chief Projects Officer",
                    "major": "Cognitive Science",
                    "email": "cpo@icb.berkeley.edu",
                    "quote": "Are you http? Because I'm :// without you",
                    "linkedin": "https://www.linkedin.com/in/chakdiya/",
                    "pic": ying,
                },
                {
                    "id": 6,
                    "name": "Sarah Jang",
                    "role": "Chief Sustainability Officer ",
                    "major": "Economics + Sustainable Environment Design",
                    "email": "cso@icb.berkeley.edu",
                    "quote": "Would I rather be feared or loved? Both. I want peole to be afriad of how much they love me. ",
                    "linkedin": "https://www.linkedin.com/in/sarah-jang-/",
                    "pic": ying,
                }, 


            ],
            "team": [
                {   
                    "id": 0,
                    "name": "Abhinav",
                    "major": "Mechanical Engineering",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/abhinav-subramaniam-709181154/",
                    "pic": ying,
                },
                {   
                    "id": 1,
                    "name": "Alysa Liu",
                    "major": "Computer + Cognitive Science",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/alysa-liu-03357b85/",
                    "pic": ying,
                },
                {   
                    "id": 2,
                    "name": "Anika Singhania",
                    "major": "Computer Science",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/anikasinghania/",
                    "pic": ying,
                },
                {   
                    "id": 3,
                    "name": "Anisha Bellur",
                    "major": "Psychology",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/anisha-bellur-92976a1a9/",
                    "pic": ying,
                },
                {   
                    "id": 4,
                    "name": "Arpna Ganshani",
                    "major": "Public Health + Data Science",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/arpna-g/",
                    "pic": ying,
                },
                {   
                    "id": 5,
                    "name": "Bongi Fleischer",
                    "major": "Computer Science",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/bongi-fleischer-9b9575144/",
                    "pic": ying,
                },
                {   
                    "id": 6,
                    "name": "Brenda Vuong",
                    "major": "Data Science",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/brenda-vuong/",
                    "pic": ying,
                },
                {   
                    "id": 7,
                    "name": "Carissa Cui",
                    "major": "Psychology + Data Science ",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/carissacui/",
                    "pic": ying,
                },
                {   
                    "id": 8,
                    "name": "Carlos Oriol Lopez-Tenorio",
                    "major": "Data + Cognitive Science",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/carlos-oriol/",
                    "pic": ying,
                },
                {   
                    "id": 9,
                    "name": "Dan Chen",
                    "major": "Statistics",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/djasonchen/",
                    "pic": ying,
                },
                {   
                    "id": 10,
                    "name": "Luis Fernando Ayala",
                    "major": "Bioengineering + EECS",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/luisferayala/",
                    "pic": ying,
                },
                {   
                    "id": 11,
                    "name": "Malena Kleiven",
                    "major": "Sustainable Env. Design",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/malena-kleiven-7859b6242/",
                    "pic": ying,
                },
                {   
                    "id": 12,
                    "name": "Meghna Sharma",
                    "major": "Mechanical Engineering",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/meghna-t-sharma/",
                    "pic": ying,
                },
                {   
                    "id": 13,
                    "name": "Michelle Gantos",
                    "major": "Mechanical Engineering",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/michelle-gantos/",
                    "pic": ying,
                },
                {   
                    "id": 14,
                    "name": "Natalie Chu",
                    "major": "Architecture",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/natalie-chu-23369a1b5/",
                    "pic": ying,
                },
                {   
                    "id": 15,
                    "name": "Neema Rashidi",
                    "major": "Molecular Cell Biology",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/neemarashidi/",
                    "pic": ying,
                },
                {   
                    "id": 17,
                    "name": "Philippa Steinberg",
                    "major": "Molecular Cell Biology",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/philippa-steinberg-78aa031a1/",
                    "pic": ying,
                },
                {   
                    "id": 18,
                    "name": "Pradeep Mani Rathnam",
                    "major": "Computer Science",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/pradeep-m-371193205/",
                    "pic": ying,
                },
                {   
                    "id": 19,
                    "name": "Qianning Tang",
                    "major": "Sustainable Env. Design",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/qianning-tang-7b257b17a/",
                    "pic": ying,
                },
                {   
                    "id": 20,
                    "name": "Riya Tandon",
                    "major": "Molecualr Cell Biology",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/riya-tandon-b0b7a8232/",
                    "pic": ying,
                },
                {   
                    "id": 21,
                    "name": "Ryan Yu",
                    "major": "Molecualr Cell Biology",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/ryan-yu-9730a5156/",
                    "pic": ying,
                },
                {   
                    "id": 22,
                    "name": "Sunny Hsu",
                    "major":"Civil Engineering",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/sunny-hsu-5931711a2/",
                    "pic": ying,
                },
                {   
                    "id": 23,
                    "name": "Vince Han",
                    "major": "EECS + Business",
                    "quote": "",
                    "linkedin": "https://www.linkedin.com/in/vincejhan/",
                    "pic": ying,
                },
                
            ],


    }

}


export default Members